ALTER TABLE boiling_session
DROP CONSTRAINT boiling_session_public_id_unique
,
DROP CONSTRAINT boiling_session_fk_user_id,
DROP CONSTRAINT boiling_session_fk_kompor_id,
DROP CONSTRAINT boiling_session_fk_esp_id;
DROP TABLE boiling_sessions;
