basePath: /
definitions:
  models.KomporRequestBody:
    properties:
      komporName:
        type: string
    type: object
  models.UserDataResponse:
    properties:
      email:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
  models.UserLoginResponse:
    properties:
      name:
        type: string
      token:
        type: string
    type: object
  utils.Response:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
      status:
        type: string
      statusCode:
        type: integer
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/kompors:
    get:
      description: Mengembalikan daftar kompor pengguna
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.KomporRequestBody'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - ApiKeyAuth: []
      summary: GetKompors
      tags:
      - Kompors
    post:
      consumes:
      - application/json
      description: Menambahkan kompor pengguna
      parameters:
      - description: Raw json kompor data
        in: body
        name: kompor
        required: true
        schema:
          $ref: '#/definitions/models.KomporRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.KomporRequestBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
      security:
      - ApiKeyAuth: []
      summary: AddKompor
      tags:
      - Kompors
  /v1/auth/login:
    post:
      consumes:
      - application/json
      description: Endpoint untuk authentikasi dan verifikasi user
      parameters:
      - description: Raw user json data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserDataResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserLoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
      summary: Login user
      tags:
      - User
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: Endpoint untuk mendaftarkan akun user ke sistem
      parameters:
      - description: Raw User Json Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserDataResponse'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.UserDataResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Response'
      summary: Register akun user
      tags:
      - Users
securityDefinitions:
  ApiKeyAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
